### PR TITLE
Fix #295: Hash history fails to save state on IE 11 when served over file protocol

### LINKED ISSUE #295: Hash history fails to save state on IE 11 when served over file protocol
IE 11 does not expose a `window.sessionStorage` object when the page is served over the file protocol. The causes the `saveState` method in `DOMStateStorage` to fail. Since creating the history with `query=false` was deprecated in version 3.0.0, I am unable to use hash history in this scenario.

I noticed similar scenarios in Chrome/Firefox/Safari throw security exceptions which are handled, and the failure is simply logged. Can we add a similar behaviour if `window.sessionStorage` is undefined?

### PR DESCRIPTION
**Pull request by lucaas**
`window.sessionStorage` is undefined in Internet Explorer when served via file protocol.
Ignore the error and return undefined in readState/setState.

Fixes #295

### CODE REVIEW

File: modules/DOMStateStorage.js [hunk 1]
```diff
@@ -20,6 +20,17 @@ export const saveState = (key, state) => {
       window.sessionStorage.setItem(createKey(key), JSON.stringify(state))
     }
   } catch (error) {
+    if (!window.sessionStorage) {
```
Comment (taion) [inline modules/DOMStateStorage.js]: Check this before attempting to write... no point in catching this as an exception

File: modules/DOMStateStorage.js [hunk 2]
```diff
@@ -50,6 +61,17 @@ export const readState = (key) => {
   try {
     json = window.sessionStorage.getItem(createKey(key))
   } catch (error) {
+    if (!window.sessionStorage) {
+      // Session storage is not available or hidden.
+      // sessionStorage is undefined in Internet Explorer when served via file protocol.
+      warning(
+        false,
+        '[history] Unable to save state; sessionStorage is not accessible'
```
Comment (taion) [inline modules/DOMStateStorage.js]: this is attempting to "read", not "save"

**Comment by lucaas** [comment]
I've now updated it to check before trying to access the object and removed the readState check, since it doesn't re-throw the error.

**Comment by mjackson** [comment]
Thanks, @lucaas! :D
